version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "gomod"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "chore(dependabot): "
      prefix: "fix(dependabot): "
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "patch"