version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - mnd
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 16
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 16
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    iface:
      enable:
        - unused
        - opaque
    lll:
      line-length: 150
    misspell:
      locale: US
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: internal/api/message_handler_test.go
        text: 'G404:'
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
